
// Windows system error message language
#define __TIMING_SYSTEM_ERROR_MESSAGE_LANG       LANG_NEUTRAL     // e.g. LANG_NEUTRAL, LANG_CHINESE, LANG_ENGLISH
#define __TIMING_SYSTEM_ERROR_MESSAGE_SUBLANG    SUBLANG_DEFAULT  // e.g. SUBLANG_DEFAULT, SUBLANG_ENGLISH_US
